### ISSUE TITLE
Complete NotImplemented items in Meadow.Linux

### ISSUE THREAD

**Issue by ctacke** [WildernessLabs/Meadow.Core#314]

**Comment by FraserElectronics** [comment]
@ctacke Chris, not sure if this is the appropriate place to discuss this, but...

I am using Meadow support in Avalonia for the Raspberry Pi and am attempting to create a PWM signal on GPIO12 on the Pi using the following code:

```
_powerControlPin = App.Device!.CreatePwmPort( App.Device.Pins.GPIO12, new Frequency( 1000, Frequency.UnitType.Hertz ), 0f );
_powerControlPin.Start();
...
...
private IPwmPort? _powerControlPin = null;
```

When I build and run this Avalonia application on the Raspberry Pi, I get the following exception:

```
Initializing OS...
Using default app.config.yaml...
Log level: Information
Platform does not support gpiod
UnhandledException
 System.NotImplementedException: The method or operation is not implemented.
   at Meadow.Linux`1.CreatePwmPort(IPin pin, Frequency frequency, Single dutyCycle, Boolean invert)
   at AVAMeadow.ViewModels.MainViewModel..ctor()
   at AVAMeadow.App.OnFrameworkInitializationCompleted()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at LinuxFramebufferPlatformExtensions.StartLinuxDirect(AppBuilder builder, String[] args, IOutputBackend outputBackend, IInputBackend inputBackend)
   at LinuxFramebufferPlatformExtensions.StartLinuxDrm(AppBuilder builder, String[] args, String card, Double scaling, IInputBackend inputBackend)
   at AVAMeadow.Desktop.Program.Main(String[] args)
Update Service is disabled.
IMeadowDevice is Linux`1
```

Before I go deeper into this Rabbit hole, how much of Meadow hardware access is available on Linux at present?

Andy
